"""Torna id_filme opcional para filmes cadastrados localmente

Revision ID: 0002_nullable_id_filme
Revises: 0001_initial_movie_schema
Create Date: 2026-09-25 01:06:19.177337

Downgrade só é possível enquanto nenhum filme tiver id_filme nulo:
a coluna volta a ser NOT NULL e a cópia da tabela falharia.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0002_nullable_id_filme'
down_revision: Union[str, Sequence[str], None] = '0001_initial_movie_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_movies', schema=None) as batch_op:
        batch_op.alter_column('id_filme',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_movies', schema=None) as batch_op:
        batch_op.alter_column('id_filme',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
