"""Cria índice de popularidade para a ordenação do catálogo

Revision ID: 0003_fact_popularidade_index
Revises: 0002_nullable_id_filme
Create Date: 2026-09-25 08:29:56.448303

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0003_fact_popularidade_index'
down_revision: Union[str, Sequence[str], None] = '0002_nullable_id_filme'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_movies_performance', schema=None) as batch_op:
        batch_op.create_index('ix_fact_movies_performance_popularidade', ['popularidade', 'sk_movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_movies_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_movies_performance_popularidade')

    # ### end Alembic commands ###
